version: '3.1'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  djangoweb:
    build: ./management_django_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./management_django_service:/django_code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: on-failure  
    depends_on:
      - db


volumes:
  postgres_data:      
