version: '3'

services:
  
  djangoweb:
    build: ./management_django_service
    command: >
        sh -c "python manage.py wait_for_db && 
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./management_django_service:/django_code
    ports:
      - "8000:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=management_django_service
      - DB_USER=postgres_user
      - DB_PASS=supersecret
    restart: on-failure  
    depends_on:
      - db
  
  
  db:
    image: postgres:11-alpine
    environment: 
      - POSTGRES_DB=management_django_service
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   

volumes:
  postgres_data:      
