version: '3.1'

services:
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=managment_django_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  djangoweb:
    build: ./management_django_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./management_django_service:/django_code
    ports:
      - "8000:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=managment_django_service
      - DB_USER=postgres
      - DB_PASS=supersecret
    stdin_open: true
    tty: true
    restart: on-failure  
    depends_on:
      - db


volumes:
  postgres_data:      
