# Generated by Django 2.2.1 on 2019-05-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_name', models.CharField(max_length=300)),
                ('runner_birth', models.PositiveIntegerField()),
                ('time_result', models.DurationField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Race')),
            ],
        ),
    ]
