# Generated by Django 2.2.1 on 2019-05-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_raceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='api.Race'),
        ),
    ]
