# Generated by Django 2.2.1 on 2019-05-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190514_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceresult',
            options={'ordering': ['time_result'], 'verbose_name_plural': 'race_results'},
        ),
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('runner_name', 'runner_birth', 'time_result')},
        ),
    ]
