# Generated by Django 2.2.1 on 2019-05-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190517_0754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('race', 'runner_name', 'runner_birth', 'time_result')},
        ),
    ]
