# Generated by Django 2.2.2 on 2019-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190604_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Woman')], max_length=1, null=True),
        ),
    ]
