# Generated by Django 2.2.2 on 2019-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_raceresult_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='itra_race_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
